version: "2"

services:
  web:
    build: ./
    image: winzig_web
    volumes:
      - .:/opt/winzig
    working_dir: /opt/winzig
    hostname: wz-web
    command: /usr/local/bin/flask run --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=winzig
      - PYTHONPATH=/opt/winzig

  redis.local:
    hostname: wz-redis
    image: redis
