"""Created url_maps table

Revision ID: 34c00ec467f6
Revises:
Create Date: 2017-01-24 16:07:40.884934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c00ec467f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_maps',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(length=2083), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_url_maps_url'), 'url_maps', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_maps_url'), table_name='url_maps')
    op.drop_table('url_maps')
    # ### end Alembic commands ###
